export type AvailablePages =
  | 'summary'
  | 'mentions'
  | 'authors'
  | 'analysis'
  | 'comparison'
  | 'infographic'
  | 'pr_dashboard'
  | 'trendings'
  | 'correction'
  | 'project_settings'
  | 'profile_analysis'
  | 'ocean_analysis'
  | 'emotion_analysis'
