parameters:
  date:
    in: query
    name: date
    description: Date
    schema:
      $ref: '#/definitions/user_defined/date_format'
  page:
    in: query
    name: page
    description: Page (Pagination)
    schema:
      $ref: '#/definitions/user_defined/page'
  package_field:
    in: query
    name: type
    description: Package Types
    schema:
      # $ref: '#/definitions/generals/string'
      type: string
      enum: 
        - menu
        - available_keyword_number
        - channels
        - projects
        - can_edit
        - max_projects
        - max_date
  limit:
    in: query
    name: limit
    description: Limit Data
    schema:
      $ref: '#/definitions/user_defined/limit'
  project:
    in: query
    name: project
    description: Multiple projects separated by comma
    schema:
      $ref: '#/definitions/user_defined/project'
  single_project:
    in: query
    name: project
    description: Single Project(Only Accept One Project Id)
    schema:
      $ref: '#/definitions/user_defined/project'
  project_fields:
    in: query
    name: selected_fields
    description: Multiple project with comma separated
    explode: false
    schema:
      type: array
      items:
        type: string
        enum: [key_id, temporary_token, key_client_id, key_name, key_word, key_include, key_exclude]
      collectionFormat: csv  
  since:
    in: query
    name: since
    example: '2023-11-01'
    schema:
      $ref: '#/definitions/user_defined/date_format'
  until:
    in: query
    name: until
    example: '2023-11-10'
    schema:
      $ref: '#/definitions/user_defined/date_format'
  timesince:
    in: query
    name: timesince
    example: '00:00'
    schema:
      $ref: '#/definitions/user_defined/time_format'
  timeuntil:
    in: query
    name: timeuntil
    example: '23:59'
    schema:
      $ref: '#/definitions/user_defined/time_format'
  q:
    in: query
    name: q
    schema:
      $ref: '#/definitions/generals/string'
  taging:
    in: query
    name: taging
    schema:
      $ref: '#/definitions/generals/string'
  service_category:
    in: query
    name: service_category
    schema:
      $ref: '#/definitions/user_defined/service_category'
  section:
    in: query
    name: section
    schema:
      $ref: '#/definitions/user_defined/section'
  author:
    in: query
    name: author
    description: user.real_name
    schema:
      $ref: '#/definitions/generals/string'
  username:
    in: query
    name: username
    description: user.name
    schema:
      $ref: '#/definitions/generals/string'
  domain:
    in: query
    name: domain
    schema:
      $ref: '#/definitions/generals/string'
  filter_bot:
    in: query
    name: filter_bot
    schema:
      $ref: '#/definitions/generals/boolean'
  type:
    in: query
    name: type
    schema:
      $ref: '#/definitions/user_defined/type'
  group_service:
    in: query
    name: group_service
    schema:
      $ref: '#/definitions/generals/boolean'
  filter_by:
    in: query
    name: filter_by
    schema:
      $ref: '#/definitions/user_defined/filter_by'
  show_total:
    in: query
    name: show_total
    schema:
      $ref: '#/definitions/generals/boolean'
  locations:
    in: query
    name: locations
    schema:
      $ref: '#/definitions/user_defined/locations'
  location_kab_kota:
    in: query
    name: location_kab_kota
    schema:
      $ref: '#/definitions/user_defined/location_kab_kota'
  screen_name:
    in: query
    name: screen_name
    schema:
      $ref: '#/definitions/generals/string'
  compare:
    in: query
    name: compare
    schema:
      $ref: '#/definitions/generals/boolean'