parameters:
  clientCode:
    in: query
    name: clientCode
    description: Code For Client
    schema:
      $ref: '#/definitions/generals/string'
  companyCode:
    in: query
    name: companyCode
    description: Code For company
    schema:
      $ref: '#/definitions/generals/string'
  Code:
    in: query
    name: code
    description: Code for Departement
    schema:
      $ref: '#/definitions/generals/string'
